// MUTATIONS
const SET_USER = "SET_USER";
const SET_TOKEN = "SET_TOKEN";
const SET_ERROR = "SET_ERROR";
const SET_DOCUSER = "SET_DOCUSER";
const SET_AVATAR_DATA = "SET_AVATAR_DATA";
const SET_AVATAR_URL = "SET_AVATAR_URL";
const SET_LOADING = "SET_LOADING";
const SET_USER_LOADING = "SET_USER_LOADING";
const SET_LOGGED_IN = "SET_LOGGED_IN";
const SET_PASSWORD = "SET_PASSWORD";

// GETTERS
const GET_USER = "GET_USER";

export {
  SET_USER,
  GET_USER,
  SET_TOKEN,
  SET_ERROR,
  SET_DOCUSER,
  SET_AVATAR_DATA,
  SET_AVATAR_URL,
  SET_LOADING,
  SET_USER_LOADING,
  SET_LOGGED_IN,
  SET_PASSWORD
};
